### ISSUE TITLE
How to configure filebeat.yml 

### ISSUE THREAD

**Issue by roiromanoclick** [pcfens/puppet-filebeat#182] opened 2018-08-08 07:51 UTC
where in the module i should configure the yml filebeate configuration?
i want the puppet install it automaticlly for all my clients.

**Comment by roiromanoclick** [comment] 2018-08-08 08:09
related to case #181

**Comment by pcfens** [comment] 2018-08-08 14:30
Closing as a duplicate of #181

**Closed by pcfens** 2018-08-08 14:30 UTC
Labels: duplicate
