### ISSUE TITLE
"Duplicate declaration: File[undef] is already declared" on Windows system

### ISSUE THREAD

**Issue by sandfred** [pcfens/puppet-filebeat#26] opened 2016-05-16 22:45 UTC
Receiving the following message when updating the agent on a Windows 2008 R2 system:

Duplicate declaration: File[undef] is already declared in file /etc/puppet/environments/env/modules/filebeat/manifests/install/windows.pp:7; cannot redeclare at /etc/puppet/environments/env/modules/filebeat/manifests/install/windows.pp:11

windows.pp contents:
`class filebeat::install::windows {
  $filename = regsubst($filebeat::download_url, '^https.*\/([^\/]+)\.[^.].*', '\1')
  $foldername = 'Filebeat'

  file { $filebeat::tmp_dir:
    ensure => directory
  }

  file { $filebeat::install_dir:
    ensure => directory
  }

  remote_file {"${filebeat::tmp_dir}/${filename}.zip":
    ensure      => present,
    source      => $filebeat::download_url,
    require     => File[$filebeat::tmp_dir],
    verify_peer => false,
  }

  exec { "unzip ${filename}":
    command  => "\$sh=New-Object -COM Shell.Application;\$sh.namespace((Convert-Path '${filebeat::install_dir}')).Copyhere(\$sh.namespace((Convert-Path '${filebeat::tmp_dir}/${filename}.zip')).items(), 16)",
    creates  => "${filebeat::install_dir}/Filebeat",
    provider => powershell,
    require  => [
      File[$filebeat::install_dir],
      Remote_file["${filebeat::tmp_dir}/${filename}.zip"],
    ],
  }

  exec { 'rename folder':
    command  => "Rename-Item '${filebeat::install_dir}/${filename}' Filebeat",
    creates  => "${filebeat::install_dir}/Filebeat",
    provider => powershell,
    require  => Exec["unzip ${filename}"],
  }

  exec { "install ${filename}":
    cwd      => "${filebeat::install_dir}/Filebeat",
    command  => './install-service-filebeat.ps1',
    onlyif   => 'if(Get-WmiObject -Class Win32_Service -Filter "Name=\'filebeat\'") { exit 1 } else {exit 0 }',
    provider =>  powershell,
    require  => Exec['rename folder'],
  }
}
`

**Comment by pcfens** [comment] 2016-05-17 01:08
What version of the puppet agent and server (if not masterless) are you running?

**Comment by sandfred** [comment] 2016-05-17 16:30
Hi pcfens,

The master is 3.8.7 and agent is 3.8.1

**Comment by pcfens** [comment] 2016-05-20 16:17
I'm having a little trouble duplicating the issue - can you share the relevant parts of the manifest?

**Comment by williamtsoi1** [comment] 2016-05-23 01:17
Hi,

I'm getting a similar error:

`Error: Failed to apply catalog: Cannot alias File[C:\temp] to ["C:/temp"]; resource ["File", "C:/temp"] already declared at /etc/puppetlabs/code/environments/playground/modules/filebeat/manifests/install/windows.pp:5`

Let me see if I can find out what's wrong. I'm using Puppet agent and server version 4.4.1

**Comment by pcfens** [comment] 2016-05-23 01:30
@williamtsoi1 - This sounds like there's already a resource `File['C:/temp']`declared in some other manifest or module. I doubt that these 2 issues are related, but likely something that can be handled more gracefully by this module. I'll take a look and try to get a fix in.

**Comment by pcfens** [comment] 2016-05-23 03:11
@williamtsoi1 - I just pushed what I think is a reasonable fix for your problem. Just like we wouldn't manage `/tmp` on a Linux system in a module like this, I removed the `tmp_dir` file resource from the module. It does to expect the directory to exist and be writable by puppet though.

**Comment by pcfens** [comment] 2016-06-13 17:20
@williamtsoi1 - Did this fix take care of your issue?

@sandfred - Were you able to resolve everything? If the issue is resolved I'd like to go ahead and close this.

**Comment by pcfens** [comment] 2016-07-05 13:22
Since I haven't heard anything back I'm going to go ahead and close this - if you're still having issues we can re-open it though.

**Closed by pcfens** 2016-07-05 13:22 UTC
Labels: bug
