### ISSUE TITLE
filebeat.modules

### ISSUE THREAD

**Issue by ronmoi** [pcfens/puppet-filebeat#143] opened 2017-11-22 00:58 UTC
Can you also add filebeat.modules  ?

**Comment by pcfens** [comment] 2017-11-22 02:47
This is a duplicate of #73, so I'm going to keep everything over there for now. Now that the template is a hash converted to a configuration file it shouldn't be too hard to put this together and include it in the config file.

**Closed by pcfens** 2017-11-22 02:47 UTC

**Comment by ronmoi** [comment] 2017-11-22 06:20
could you help me how to use pure_hash.yml.erb and params that I should use in init.pp to populate pure_hash.yml.erb ? TIA

**Comment by pcfens** [comment] 2017-11-24 03:37
If you're using version 2.0 or later you're using the pure_hash.yml.erb template by default. If you had everything working before, it will work the same after upgrading to a newer module too.

The new template converts a Puppet hash that's formed in [config.pp](https://github.com/pcfens/puppet-filebeat/blob/master/manifests/config.pp#L29-L49) into YAML.

The [usage section](https://github.com/pcfens/puppet-filebeat#usage) of the readme file hasa few examples.

**Comment by ronmoi** [comment] 2017-11-28 04:59
Thanks for the reply, but what I'm looking for is how to add the parameter "modules" under key "filebeat".
