### ISSUE TITLE
Configuration file ordering with Ruby > 1.8

### ISSUE THREAD

**Issue by stith** [pcfens/puppet-filebeat#32] opened 2016-06-30 20:16 UTC
Hey Y'all,

It seems that the config file generation for the ruby > 1.8 template sometimes results in inconsistent ordering. We're seeing things like this fairly regularly:

```
+++ /tmp/puppet-file20160630-11451-1fr4lz1      2016-06-30 13:09:32.743719846 -0700
@@ -14,8 +14,8 @@
       - team_one
   output:
     logstash:
-      port: 5044
       loadbalance: true
+      port: 5044
```

It's not a huge issue since the filebeat process maintains state just fine, but it would be really nice to be able to guarantee puppet exiting cleanly when no changes are actually being made.

**Comment by pcfens** [comment] 2016-07-05 12:33
What version of Ruby and Puppet are you using? I haven't been able to reproduce this, but I haven't been trying particularly hard either.

**Comment by Exus** [comment] 2016-08-02 08:22
Same here,

```
+++ /tmp/puppet-file20160802-26194-jsrdsz       2016-08-02 08:18:36.276471759 +0000
@@ -4,8 +4,8 @@
       - /var/log/nginx/*-access.log
       encoding: plain
       fields:
-        partition: gr
         stage: production
+        partition: gr
         cluster: www2
       fields_under_root: true
       input_type: log
```

ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
Debian Jessie 64bit

**Comment by pcfens** [comment] 2016-08-03 17:49
Hi @Exus - which version of Puppet are you using?

I'm wondering if it's time to switch to a full YAML template instead of trying to generate it all at once. The generation is nice for future proofing things, but starts to fall over if Ruby doesn't keep things consistent.

**Comment by Exus** [comment] 2016-08-04 07:47
puppet 3.7.3-1puppetlabs1
puppetmaster 3.8.2-1puppetlabs1

**Comment by Exus** [comment] 2016-08-04 08:11
I've upgrated both puppet and puppet-master to 3.8.7-1puppetlabs1
Still no luck

**Comment by pcfens** [comment] 2016-08-09 20:24
Is this only popping up in sub-hashes or is it at all levels? Unfortunately Ruby doesn't seem to document this issue very well, and I'm trying to get a better understanding of it before dropping the more open ended template entirely.

**Comment by Exus** [comment] 2016-08-16 12:45
I think that on all levels, f.e. 

```Notice: /Stage[main]/Filebeat::Config/File[filebeat.yml]/content:
--- /etc/filebeat/filebeat.yml  2016-08-16 12:06:43.684567341 +0000
+++ /tmp/puppet-file20160816-44928-1bijf3f      2016-08-16 12:41:12.806892568 +0000
@@ -3,8 +3,8 @@
   filebeat:
     registry_file: ".filebeat"
     idle_timeout: "5s"
-    config_dir: /etc/filebeat/conf.d
     publish_async: false
+    config_dir: /etc/filebeat/conf.d
     spool_size: 2048```

**Comment by netdata** [comment] 2016-09-26 12:32
I can confirm this issue as well, using ruby 2.0.0p598

**Comment by pcfens** [comment] 2016-09-26 15:46
Are you using puppet 3 as well? Puppet 4 delivers it's own version of Ruby (2.1.9 in Puppet 4.6), so I'm starting to wonder if I need to change the template switch from Ruby 1.9 to 2.1. Another option is to change everything to use a full template (it would be more Puppet like, but would require an update for every change in filebeat).

**Comment by pcfens** [comment] 2016-11-02 20:30
For filebeat v5 the default template behaves like a normal text template rather than forming the yaml from the hash, which also fixes this issue, but only for filebeat v5. Since this issue doesn't exist in puppet 4, and puppet 3 will be reaching it's end of life at the end of the year, would it cause a lot of trouble for everyone if we don't fix it in filebeat 1.x and puppet 3?

**Comment by Exus** [comment] 2016-11-13 21:11
puppet 3.8 (server / client)
filebeat v5

Same situation, popping up on prospectors
`Notice: /Stage[main]/Profiles::Nginx/Filebeat::Prospector[nginx-error]/File[filebeat-nginx-error]/content:
--- /etc/filebeat/conf.d/nginx-error.yml        2016-11-13 21:00:09.370798917 +0000
+++ /tmp/puppet-file20161113-25038-k79b71       2016-11-13 21:03:03.824571621 +0000
@@ -7,8 +7,8 @@
         - /var/log/nginx/error.log
       encoding: plain
       fields:
-        stage: beta
         partition: product
+        stage: beta
         cluster: app
       fields_under_root: true`

For me upgrading puppet 3->4 is very hard, I have plenty of incompatible code (node inheritance, etc)

**Comment by pcfens** [comment] 2016-11-14 01:27
Can you try changing [line 22 in the filebeat5.yml.erb file](https://github.com/pcfens/puppet-filebeat/blob/master/templates/filebeat5.yml.erb#L22) to 

`<%- @filebeat_config['fields'].sort.to_h.each_pair do |k, v| -%>`

to see if that fixes anything?

**Comment by Exus** [comment] 2016-11-14 09:38
No luck, the same, but I use fields in prospectors not main config.
I've tried to do similar change line 32 in prospector5.yml.erb to

`<%- @fields.sort.to_h.each_pair do |k, v| -%>`

But have error

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template filebeat/prospector5.yml.erb:
  Filepath: /etc/puppet/env-ex/modules/filebeat/templates/prospector5.yml.erb
  Line: 32
  Detail: undefined method `to_h' for [["cluster", "app2"], ["partition", "gr"], ["stage", "beta"]]:Array
 at /etc/puppet/env-ex/modules/filebeat/manifests/prospector.pp:41 on node web-gr-app2-0.v.l
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
Changed it again (to sort and iterate over array) to

`<%- @fields.sort.each do |k, v| -%>`

and... looks stable now :-)

**Comment by pcfens** [comment] 2016-12-19 13:51
Have any of you run across this using puppet 4, or just with puppet 3? I'm hoping to do some work on this module over the next couple of weeks, but with puppet 3 reaching end of life on December 31st I may just ignore this one. Thoughts?

**Comment by pcfens** [comment] 2017-02-12 05:46
Since this issue only exists with the Filebeat 1.x config template and Ruby 1.8, I'm going to close this.

The Filebeat 5.x config template shouldn't run in to this problem.

**Closed by pcfens** 2017-02-12 05:46 UTC
