### ISSUE TITLE
Config.prospectors deprecated in filebeat 6.x

### ISSUE THREAD

**Issue by fbarbeira** [pcfens/puppet-filebeat#188] opened 2018-08-31 08:40 UTC
Maybe it could be used if:  **$filebeat::major_version == 6**
```
2018-08-31T10:36:34.872+0200	WARN	[cfgwarn]	beater/filebeat.go:86	DEPRECATED: config.prospectors are deprecated, Use `config.inputs` instead. Will be removed in version: 7.0.0
```

**Comment by pcfens** [comment] 2018-08-31 17:16
Thanks!

This is a duplicate of #174. It's on the fix list for when we also drop support for filebeat pre-6.x.

**Closed by pcfens** 2018-08-31 17:16 UTC
